import { buildDailyBrief } from "@/jobs/daily-brief";
import type { AnalyticsSnapshot, CommunityItem, FeedbackEmail, FounderHubSnapshot, Insight, MemoryEntry } from "@/types/founder-hub";

const emptyValue = "Not available";

export function buildFounderHubMarkdown(snapshot: FounderHubSnapshot, generatedAt = new Date().toISOString()) {
  const brief = buildDailyBrief(snapshot);
  const sections = [
    `# Forgeko Founder Hub Export`,
    `Generated: ${generatedAt}`,
    buildSummary(snapshot),
    buildDailyBriefSection(brief),
    buildAnalyticsSection(snapshot.analytics),
    buildCommunitySection(snapshot.communityItems),
    buildFeedbackSection(snapshot.feedback),
    buildInsightsSection(snapshot.insights),
    buildMemorySection(snapshot.memory)
  ];

  return `${sections.join("\n\n").trim()}\n`;
}

export function founderHubExportFileName(generatedAt = new Date().toISOString()) {
  const timestamp = generatedAt.replace(/[:.]/g, "-");
  return `forgeko-founder-hub-export-${timestamp}.md`;
}

function buildSummary(snapshot: FounderHubSnapshot) {
  return [
    "## Snapshot Summary",
    table(
      ["Data Set", "Rows"],
      [
        ["Community items", snapshot.communityItems.length],
        ["Feedback emails", snapshot.feedback.length],
        ["Insights", snapshot.insights.length],
        ["Memory entries", snapshot.memory.length],
        ["Analytics trend rows", snapshot.analytics.trend.length]
      ]
    )
  ].join("\n\n");
}

function buildDailyBriefSection(brief: ReturnType<typeof buildDailyBrief>) {
  return [
    "## Daily Brief",
    `Generated by brief: ${brief.generatedAt}`,
    "### Priorities",
    bulletList(brief.priorities),
    "### Recommended Post",
    prose(brief.recommendedPost),
    "### Discussions To Read",
    bulletList(brief.discussionsToRead),
    "### Discussions To Reply To",
    bulletList(brief.discussionsToReplyTo),
    "### Landing Analysis",
    prose(brief.landingAnalysis),
    "### Feedback Analysis",
    prose(brief.feedbackAnalysis),
    "### Weekly Trend",
    prose(brief.weeklyTrend)
  ].join("\n\n");
}

function buildAnalyticsSection(analytics: AnalyticsSnapshot) {
  return [
    "## Analytics",
    table(
      ["Metric", "Value"],
      [
        ["Visitors", analytics.visitors],
        ["Unique visitors", analytics.uniqueVisitors],
        ["Conversions", analytics.conversions],
        ["Conversion rate", `${analytics.conversionRate}%`],
        ["Waitlist signups", analytics.waitlistSignups],
        ["Waitlist confirmed", analytics.waitlistConfirmed],
        ["Waitlist conversion rate", `${analytics.waitlistConversionRate}%`]
      ]
    ),
    "### AI Explanation",
    prose(analytics.aiExplanation),
    "### Top Referrers",
    tableOrEmpty(["Source", "Visitors"], analytics.topReferrers.map((row) => [row.source, row.visitors])),
    "### Top Pages",
    tableOrEmpty(["Path", "Visitors"], analytics.topPages.map((row) => [row.path, row.visitors])),
    "### Top Clicks",
    tableOrEmpty(["Label", "Href", "Clicks"], analytics.topClicks.map((row) => [row.label, row.href, row.clicks])),
    "### Waitlist Sources",
    tableOrEmpty(["Source", "Signups"], analytics.waitlistSources.map((row) => [row.source, row.signups])),
    "### First-party Events",
    tableOrEmpty(["Event Type", "Count"], analytics.pageEvents.map((row) => [row.eventType, row.count])),
    "### Trend",
    tableOrEmpty(["Date", "Visitors"], analytics.trend.map((row) => [row.date, row.visitors]))
  ].join("\n\n");
}

function buildCommunitySection(items: CommunityItem[]) {
  return [
    "## Community Items",
    items.length
      ? items.map(buildCommunityItem).join("\n\n")
      : "_No community items available._"
  ].join("\n\n");
}

function buildCommunityItem(item: CommunityItem) {
  return [
    `### ${heading(item.title)}`,
    table(
      ["Field", "Value"],
      [
        ["ID", item.id],
        ["Source", item.source],
        ["Author", item.author],
        ["URL", item.url],
        ["Created at", item.createdAt],
        ["Relevance score", item.relevanceScore],
        ["Pain point", item.painPoint]
      ]
    ),
    "#### Summary",
    prose(item.summary),
    "#### User Language",
    bulletList(item.userLanguage),
    "#### Post Angle",
    prose(item.postAngle),
    "#### Suggested Reply",
    prose(item.suggestedReply),
    "#### Reply Rationale",
    prose(item.replyRationale)
  ].join("\n\n");
}

function buildFeedbackSection(emails: FeedbackEmail[]) {
  return [
    "## Feedback",
    emails.length
      ? emails.map(buildFeedbackEmail).join("\n\n")
      : "_No feedback emails available._"
  ].join("\n\n");
}

function buildFeedbackEmail(email: FeedbackEmail) {
  return [
    `### ${heading(email.subject)}`,
    table(
      ["Field", "Value"],
      [
        ["ID", email.id],
        ["From", email.from],
        ["Category", email.category],
        ["Created at", email.createdAt],
        ["Pain point", email.painPoint],
        ["Snippet", email.snippet]
      ]
    ),
    "#### Summary",
    prose(email.summary)
  ].join("\n\n");
}

function buildInsightsSection(insights: Insight[]) {
  return [
    "## Insights",
    insights.length
      ? insights.map(buildInsight).join("\n\n")
      : "_No insights available._"
  ].join("\n\n");
}

function buildInsight(insight: Insight) {
  return [
    `### ${heading(insight.title)}`,
    table(
      ["Field", "Value"],
      [
        ["ID", insight.id],
        ["Created at", insight.createdAt],
        ["Evidence IDs", insight.evidenceIds.join(", ")]
      ]
    ),
    "#### Summary",
    prose(insight.summary)
  ].join("\n\n");
}

function buildMemorySection(entries: MemoryEntry[]) {
  return [
    "## Memory",
    entries.length
      ? entries.map(buildMemoryEntry).join("\n\n")
      : "_No memory entries available._"
  ].join("\n\n");
}

function buildMemoryEntry(entry: MemoryEntry) {
  return [
    `### ${heading(entry.title)}`,
    table(
      ["Field", "Value"],
      [
        ["ID", entry.id],
        ["Date", entry.date],
        ["Sources", entry.sources.join(", ")]
      ]
    ),
    "#### Motivation",
    prose(entry.motivation),
    "#### Consequences",
    prose(entry.consequences)
  ].join("\n\n");
}

function tableOrEmpty(headers: string[], rows: Array<Array<string | number>>) {
  return rows.length ? table(headers, rows) : "_No rows available._";
}

function table(headers: string[], rows: Array<Array<string | number>>) {
  const header = `| ${headers.map(tableCell).join(" | ")} |`;
  const divider = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.map(tableCell).join(" | ")} |`);
  return [header, divider, ...body].join("\n");
}

function bulletList(items: string[]) {
  return items.length ? items.map((item) => `- ${inline(item)}`).join("\n") : "_No rows available._";
}

function prose(value: string) {
  return normalize(value);
}

function heading(value: string) {
  return inline(value);
}

function inline(value: string | number) {
  return normalize(String(value)).replace(/\s+/g, " ");
}

function tableCell(value: string | number) {
  return inline(value).replace(/\|/g, "\\|") || emptyValue;
}

function normalize(value: string) {
  return value.trim() || emptyValue;
}
